// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD97XIKx1GndTJwkanOTMHQJ1_FVc-T8Pw',
    appId: '1:936383223494:web:a58c82b78dc57dbd76e9c7',
    messagingSenderId: '936383223494',
    projectId: 'fffw-web',
    authDomain: 'fffw-web.firebaseapp.com',
    storageBucket: 'fffw-web.appspot.com',
    measurementId: 'G-5F8PMBJ3ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxaSo-jgm3QOrIDRdVMggh7dilbqQQ20',
    appId: '1:936383223494:android:80afcd49919d6a9076e9c7',
    messagingSenderId: '936383223494',
    projectId: 'fffw-web',
    storageBucket: 'fffw-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsq6-hqIbXTpGQhHY6dzNkF9JrfbkzX4',
    appId: '1:936383223494:ios:1ecdc00dc4a83c2876e9c7',
    messagingSenderId: '936383223494',
    projectId: 'fffw-web',
    storageBucket: 'fffw-web.appspot.com',
    iosClientId: '936383223494-3ttlqj2bb2s01gkfumtfj0f8cmj59kl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.emptyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTsq6-hqIbXTpGQhHY6dzNkF9JrfbkzX4',
    appId: '1:936383223494:ios:1ecdc00dc4a83c2876e9c7',
    messagingSenderId: '936383223494',
    projectId: 'fffw-web',
    storageBucket: 'fffw-web.appspot.com',
    iosClientId: '936383223494-3ttlqj2bb2s01gkfumtfj0f8cmj59kl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.emptyApp',
  );
}
